In [28]:
from numpy import *

In [29]:
tab1 = array([1, 2, 3, 4, 5])

tab1[::-1]

array([5, 4, 3, 2, 1])

In [30]:
tab1 = array([1, 2, 3, 4, 5])

tab1[::2]*10

array([10, 30, 50])

In [31]:
tab1 = array([1, 2, 3, 4, 5])

tab1[::2]*tab1[::2]

array([ 1,  9, 25])

In [32]:
tab1 = array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(tab1.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
c = array([[1, 2, 3], [4, 5, 6]])

print(c[:, 1])

[2 5]


In [34]:
n = 9

tab1 = arange(1, n+1).reshape(3, 3)

tab2 = tab1*10

tab3 = concatenate((tab1, tab2),axis= 1)
print(tab3)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


Question 7 : (PAS FINIE)

In [81]:
n = 9
#All 1
tab_start_last = ones((1, n))
one =arange(1) +1
table2 = ones((n-2, n))  +1 

table = concatenate((tab_start_last,table2,tab_start_last),axis = 0)



print(table)

#print(element2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Question 8 : 